#!/bin/bash
# Launches start jekyll server and opens the server with the safari browser, after closing the browser, the jekyll server is also stopped. 

cd /Users/lucdejaegher/Documents/fabilicious.github.io

bundle exec jekyll serve & 
sleep 5
open -WFn -a "Google Chrome" http://127.0.0.1:4000

